
Map<String, String> knotMap = {
'SheepShank.gif': 'Unreliable knot used to shorten a length of rope.',
'WaterBowline.gif': 'A Bowline with an additional turn for greater security.',
'TwoHalfHitches.gif': 'Excellent way of securing a rope to a post or ring.',
'TruckerHitchQuick.gif': 'Quick-release method of securing a load or tarpaulin.',
'TruckerHitch.gif': 'Valuable knot usually used for securing loads or tarpaulins.',
'TimberHitch.gif': 'Simple knot commonly used for towing a log.',
'SquareKnot.gif': 'Simple way to join two ropes made up of two Half Knots.',
'SpanishBowline.gif': 'Creates two loops for tying around legs in an emergency.',
'SnellKnot.gif': 'Allows the leader, or tippet, to be directly tied to a baited hook.',
'SlipKnot.gif': 'Simple loop in rope\'s end - loosens when tail end is pulled.',
'SlidingDoubleFisherman.gif': 'Creates a Prusik Loop with an adjustable length eye.',
'SingleRopeBraid.gif': 'Demonstrates three-stranded braiding using a single rope.',
'SheetBend.gif': 'Joins two ropes of unequal, or similar, size.',
'RunningBowline.gif': 'Bowline encircles the standing end to create a noose.',
'QuickHitch.gif': 'Arborist\'s method of pulling one rope aloft using another.',
'OverhandKnot.gif': 'The simplest of the Single-Strand Stopper Knots.',
'OneHandedBowline.gif': 'Allows the Bowline to be tied using one hand.',
'NooseKnot.gif': 'Creates a loop that tightens when pulled.',
'MidshipmanHitch.gif': 'An adjustable loop tied using a Rolling Hitch',
'LashingTripod.gif': 'Joins three poles to one another for use as a tripod.',
'LashingSquare.gif': 'Binds two poles together at a 90-degree angle',
'LashingShear.gif': 'Joins two poles with other ends apart as shear legs.',
'LashingRound.gif': 'Securely binds two poles together to make an end join.',
'LashingDiagonal.gif': 'Secures diagonal braces to hold a structure rigid.',
'HalfHitch.gif': 'Used to tie rope around an object and back to itself.',
'FigureEightKnot.gif': 'Non-binding, quick and convenient stopper knot.',
'FigureEightDoubleLoop.gif': 'Stable double loop in the middle of a piece of rope.',
'FigureEightBend.gif': 'Secure, simple method for joining two ropes.',
'DoubleFisherman.gif': 'Creates a Prusik Loop with an adjustable length eye.',
'DoubleOverhandStopper.gif': 'Makes a reliable, moderately large, stopper knot.',
'CowHitchLoops.gif': 'Temporary hitch for a light load or animal.',
'CowHitchEnds.gif': 'Temporary hitch for a light load or animal.',
'CoilUnattachedRope.gif': 'Secure and neat rope storage, minimizes tangles and twists.',
'CloveHitchLoops.gif': 'Simple (weak) hitch to attach a rope to a pole or ring',
'CloveHitchEnd.gif': 'Temporary hold, e.g., stage scenery or mooring buoy',
'CLoveHitch.gif': 'Simple (weak) hitch to attach a rope to a pole or ring',
'BowlineKnot.gif': 'Reasonably secure loop in a rope\'s end - and easy to undo.',
'BarrelHitch.gif': 'Secure method to lift barrels, buckets and other containers.',
'AnchorHitch.gif': 'Excellent knot to attach an anchor line to an anchor.',
'AdjustableGripHitch.gif': 'Used to tension a rope, e.g.,  a tent ridge line or a guy line.'
};
